# Generated by Django 2.1.4 on 2019-02-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
