# Generated by Django 2.2 on 2019-05-03 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=35, unique=True, validators=[django.core.validators.RegexValidator('^[0-9@a-zA-Z]*&', 'Only alphanumeric characters are allowed')])),
                ('password', models.CharField(max_length=15)),
                ('confirm_password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=35, unique=True, validators=[django.core.validators.RegexValidator('^[0-9@a-zA-Z]*&', 'Only alphanumeric characters are allowed')])),
                ('password', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user_registration')),
            ],
        ),
    ]
