# Generated by Django 2.2 on 2019-05-03 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='mobile',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
