# Generated by Django 2.2 on 2019-05-03 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190503_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='email',
            field=models.CharField(max_length=35, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='email',
            field=models.CharField(max_length=35, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
